### ISSUE TITLE
16. In PMIS tab changes in all pages

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/pmis#16]
0. There will be 2 tab. e.g. List & Create.
1. when user will click on the  "List" tab then page will be refreshed and tab name will be changed to "List" & "Create". 
2. "Back" button will be added in the create/edit page. when click on the "Back" button then page will be refreshed and tab name will be changed to "List" & "Create". 
3. . When user will click on the "Edit" button in the list then "Create" tab title will be changed to "Edit" tab title.
4. In Edit mode, "Save" button will be changed to "Update" button.
![image](https://user-images.githubusercontent.com/52368063/60413747-c6708100-9bf7-11e9-9909-b0f6893eba12.png)

**Comment by mypayroll** [comment]
It's done now.

**Comment by aminshaka** [comment]
1 and 2 are not fixed yet.

**Comment by mypayroll** [comment]
Please mention the name here.
