### ISSUE TITLE
17. In PMIS-Language page "LPDS" button is not working.

### ISSUE THREAD

**Issue by AnikaMollik** [collecteddoc/pmis#17]
![image](https://user-images.githubusercontent.com/52368063/60415748-ddb26d00-9bfd-11e9-9cbb-2fe3a95035b6.png)

**Comment by mypayroll** [comment]
It's done now.

**Comment by aminshaka** [comment]
After click on "SPDS", "LPDS" a new blank tab is open named 'Untitled'. Not need to open a new tab.

![image](https://user-images.githubusercontent.com/52271735/61032581-8a9d9e80-a3e3-11e9-9626-db663fc4b8f1.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/61628273-75f0be80-ac9f-11e9-8c74-82e07cd74a1d.png)



Please check image.
It's working perfect on live link as well.
