### ISSUE TITLE
24. Please separate the Entry filed and read only filed into two block in the General Information. Entry fields are first then Read only fields. And don't put "*" symbol in the read only fields. 

### ISSUE THREAD

**Issue by hafiz-eng** [collecteddoc/pmis#24]
![02](https://user-images.githubusercontent.com/52373162/60683332-0e71fb00-9eb9-11e9-8e05-6c2adaa557f3.jpg)

**Comment by mypayroll** [comment]
I had make two section where one is for entry field and other is for read-only field.
Now i removed * from all read-only  fields.

**Comment by aminshaka** [comment]
Bug fixed
