### ISSUE TITLE
27. At General Information, after click on Edit, all information are not loading

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/pmis#27]
![image](https://user-images.githubusercontent.com/52271735/60961989-1c979f80-a32f-11e9-86a8-d54f4ebe19ea.png)

**Comment by mypayroll** [comment]
![image](https://user-images.githubusercontent.com/52411235/61629010-68d4cf00-aca1-11e9-8629-acb962c30ca9.png)

For that 
you have to change according functionality like
if you add spouse with that gov id then you will see new upgraded record in general information.
