### ISSUE TITLE
5. Title should be same as menu. The tab name should be 'List', 'Edit', 'Create'.

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/pmis#6]
![image](https://user-images.githubusercontent.com/52271735/60271510-4d7dda80-9914-11e9-862e-225d717c65d8.png)

**Comment by mypayroll** [comment]
It's done now.

**Comment by aminshaka** [comment]
Title should be same as menu. That means it should be dynamic. If change the menu name then title will be changed automatically.

**Comment by mypayroll** [comment]
Title is same as menu and yes it will change dynamically.
